#!/usr/bin/env python3
"""Render a cautious comparison report; unknown anchors remain explicitly unknown."""
import argparse
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--manifest',required=True); ap.add_argument('--inventory',required=True)
    ap.add_argument('--out',required=True); ap.add_argument('--proximity',action='append',default=[])
    args=ap.parse_args()
    manifest=json.loads(Path(args.manifest).read_text(encoding='utf-8'))
    inventory=json.loads(Path(args.inventory).read_text(encoding='utf-8'))
    lines=[]
    def p(s=''): lines.append(str(s))
    p('ANALYSE COMPARATIVE MULTIMEDIA — MOBIWIRE NIKITI / ALTICE F2')
    p('Analyse hors ligne et en lecture seule. Rapport généré à partir des fichiers explicitement fournis.')
    p('')
    p('Firmware témoin :')
    p('  '+manifest.get('reference_claim','non identifié'))
    p('  Source fournie : '+manifest.get('source','inconnue'))
    found=manifest.get('identification_markers',{})
    p('  Marqueurs d’identification binaires : '+json.dumps(found,ensure_ascii=False))
    p('Proximité avec Altice :')
    if args.proximity:
        for path in args.proximity:
            d=json.loads(Path(path).read_text(encoding='utf-8'))
            p(f"  {d.get('witness_label')}: fonctions {d['witness_functions']}/{d['altice_functions']}; "
              f"empreintes exactes opérandes {d['exact_relocated_instruction_sequence_matches']}; "
              f"paires alignées {d['one_to_one_high_confidence_function_pairs']}; "
              f"code alignable {d['alignable_proportion_vs_smaller_image']:.3f}; "
              f"call graph {d['call_graph_edge_preservation']:.3f}")
    else: p('  NON MESURÉE : aucune ALICE témoin admissible fournie.')
    p('Preuve même famille :')
    p('  ELKI : les documents locaux associent ce build au NIKITI/F2 V01; aucun binaire correspondant n’a été trouvé.')
    p('  Les marqueurs du dump présent identifient seulement ALTICE_F2_DS_V02.1_181023_MP / DL188_GX1882_NIKITI.')
    p('')
    p('Ancrage des menus (aucune fonction déduite d’une différence non ancrée) :')
    p('  Export témoins / Altice disponibles : '+json.dumps(inventory,ensure_ascii=False))
    p('  Les références de chaînes Audio/Video/FM/Image servent d’indices; une table de menu doit être corroborée par les handlers/call graph.')
    p('')
    p('Conclusion obligatoire')
    p('Firmware témoin : '+('ELKI indisponible' if not manifest.get('alice') else manifest.get('reference_claim','à vérifier')))
    p('Proximité avec Altice : '+('NON MESURÉE' if not args.proximity else 'voir scores techniques ci-dessus'))
    p('Preuve même famille : documentaire pour le modèle/HW V01; aucune preuve binaire ELKI locale')
    p('')
    p('FM Radio :')
    p('témoin adresse : INCERTAIN — aucun ALICE ELKI disponible')
    p('Altice adresse : INCERTAIN — à relier aux chaînes et à la table Multimedia')
    p('')
    p('Image Viewer :')
    p('témoin adresse : INCERTAIN — aucun ALICE ELKI disponible')
    p('Altice adresse : INCERTAIN — à relier aux chaînes et à la table Multimedia')
    p('')
    p('Audio Player :')
    p('entrée menu témoin : INCERTAIN — manuel connu, firmware binaire absent')
    p('fonction launch : INCERTAIN')
    p('fonction init : INCERTAIN')
    p('équivalent Altice : INCERTAIN')
    p('état = INCERTAIN')
    p('')
    p('Video Player :')
    p('entrée menu témoin : INCERTAIN — manuel connu, firmware binaire absent')
    p('fonction launch : INCERTAIN')
    p('fonction init : INCERTAIN')
    p('équivalent Altice : INCERTAIN')
    p('état = INCERTAIN')
    p('')
    p('Hypothèse minimale de modification : INCONNUE jusqu’à comparaison des structures de menu et des fonctions d’initialisation ancrées.')
    p('Un simple patch du menu semble possible : INCERTAIN')
    p('Raison : sans savoir si les handlers et le moteur média survivent dans Altice, un patch seul n’est pas démontré.')
    p('')
    p('Outillage prêt :')
    p('  prepare_f2_reference.py --input <ZIP|dump BIN|dossier Firmware> --out <dossier témoin> --analyze')
    p('  La base Ghidra vient de l’en-tête ALICE offset 8. ALICE_1/2, VIVA, composants, hashes et rapports sont conservés.')
    p('  compare_f2_reference.py mesure le code alignable, les fingerprints, le graphe d’appels et les références texte.')
    p('  Aucun patch firmware ou fichier destiné au flash n’est produit.')
    p('')
    p('Fichier à obtenir en priorité : une archive ZIP complète du package SP Flash')
    p('ELKI_DS_L_V01.2_181106_MP, ou le dump complet 4 MiB de ce build;')
    p('un dossier Firmware/ extrait contenant CFG, BOOTLOADER, EXT_BOOTLOADER, ROM et VIVA convient également.')
    p('Les seules archives du workspace sont le ZIP QMobile déjà connu et le RAR Altice actuel; aucun NAKAI local non plus.')
    p('Le QMobile n’est pas utilisé comme témoin principal.')
    p('')
    p('Inventaire récursif : '+str(Path(args.inventory)))
    Path(args.out).write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(Path(args.out))

if __name__=='__main__': main()
